// import { Geist, Geist_Mono ,GeistMono } from "next/font/google";
import "./globals.css";
import "./app.css";
import 'bootstrap/dist/css/bootstrap.css';
import './css/bootstrap.css'
import './css/responsive.css'
import './css/bootstrap.min.css'
import Providers from "./Providers";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
